feat: zstd compression support

diff --git a/tests/Makefile.am b/tests/Makefile.am
--- a/tests/Makefile.am
+++ b/tests/Makefile.am
@@ -18,7 +18,7 @@ clean-local:
 	-rm -f *.tmp core *.o *.bak *~ *% *\# TAGS gmon.out \#*\# dupa*
 	-find sh -name \*~ | xargs -r rm
 
-check: poldek_test_conf.conf
+tests: poldek_test_conf.conf
 	$(MAKE) check-am
 	-rm -f poldek_test_conf.*
 
@@ -38,21 +38,28 @@ check: poldek_test_conf.conf
 	strip $@
 	rm -f $<
 
-sheck:
+sh-tests:
 	@echo; echo "Running *.sh tests";  \
 	find sh -name \*~ | xargs -r rm;   \
-	n=0; nok=0;                        \
+	nth=0; nok=0;           	   \
 	for i in sh/[0-9][0-9]*; do        \
 	  [ -f $$i ] || continue;          \
-	  n=$$(expr $$n + 1);              \
-	  sh $$i -n 10; 		   \
-          if [ $$? -eq 0 ]; then           \
-            nok=$$(expr $$nok + 1);     \
-            echo "  ## $$i PASSED";     \
-          else                          \
-            echo "  ## $$i FAILED";     \
-          fi;                           \
-	done;                           \
+	  cmpr="gz"; suffixed=""; 	   \
+	  grep -q compr-setup $$i;	   \
+	  [ $$? -eq 0 ] && cmpr="gz zst none" && suffixed="1"; \
+	  for c in $$cmpr; do		   \
+	     COMPR="$$c"; export COMPR;    \
+	     suffix=""; [ -n "$$suffixed" ] && suffix=" ($$c)"; \
+	     nth=$$(expr $$nth + 1);       \
+	     sh $$i -n 10; 		   \
+	     if [ $$? -eq 0 ]; then        \
+	    	nok=$$(expr $$nok + 1);    \
+		echo "  ## $$i$$suffix PASSED";    \
+	     else                          \
+		echo "  ## $$i$$suffix FAILED";    \
+	     fi;                           \
+	   done;                           \
+	done;                              \
 	echo "====================================="; \
-	echo " Passed $$nok tests of total $$n";      \
+	echo " Passed $$nok tests of total $$nth";      \
 	echo "====================================="
diff --git a/tests/sh/01-create-repo b/tests/sh/01-create-repo
--- a/tests/sh/01-create-repo
+++ b/tests/sh/01-create-repo
@@ -13,18 +13,18 @@ Case_f="-n foo                    =>  dir (or original type) -> foo's type"
 Case_g="-s /foo --mkidx=/tmp/bar.gz"
 Case_h="-n foo --mkidx=/tmp/bar.gz"
 
-
 . ./sh/lib/setup
 . ./sh/lib/repo-setup
+. ./sh/lib/compr-setup
 
 testCreateDefaultType()
 {
     msgn $Case_a
     $POLDEK_NOCONF -s $REPO --mkidx || fail "mkidx #1 failed"
-    die_if_empty_index "$REPO/packages.ndir.gz"
+    die_if_empty_index "$REPO/packages.ndir$COMPR_EXT"
 
     $POLDEK_NOCONF -s $REPO --mkidx=$TMPDIR || fail "mkidx #2 failed"
-    die_if_empty_index "$TMPDIR/packages.ndir.gz"
+    die_if_empty_index "$TMPDIR/packages.ndir$COMPR_EXT"
     if ! diff -u $REPO/packages.ndir.md $TMPDIR/packages.ndir.md; then
         fail "differ md's!"
     fi
@@ -35,7 +35,7 @@ testCreateDefaultType()
 XXXtestConvertRepos()           # disabled as pdir indexes are gone since 0.4
 {
     $POLDEK_NOCONF -s $REPO --mkidx || fail "mkidx failed"
-    die_if_empty_index "$REPO/packages.ndir.gz"
+    die_if_empty_index "$REPO/packages.ndir$COMPR_EXT"
 
     rm -rf $TMPDIR/packages.*
     cp $REPO/packages.ndir.* $TMPDIR || fail "cp failed"
@@ -44,13 +44,13 @@ XXXtestConvertRepos()           # disabled as pdir indexes are gone since 0.4
     # c) --st type /foo --mt type =>  type -> dtype
     msgn "$Case_c"
     $POLDEK_NOCONF --st pndir -s $TMPDIR --mkidx --mt=pdir || fail "$Case_c failed"
-    die_if_empty_index "$TMPDIR/packages.dir.gz"
+    die_if_empty_index "$TMPDIR/packages.dir$COMPR_EXT"
 
     # b) --st type -s /foo
     msgn "$Case_b"
     rm -f $TMPDIR/packages.ndir*
     $POLDEK_NOCONF --st pdir -s $TMPDIR --mkidx || fail "$Case_b failed"
-    die_if_empty_index "$TMPDIR/packages.ndir.gz"
+    die_if_empty_index "$TMPDIR/packages.ndir$COMPR_EXT"
 }
 
 #  d) -s /foo --mt dtype        =>  dir  -> dtype
@@ -59,18 +59,18 @@ XXXtestSelectType() # disabled as pdir indexes are gone since 0.4
 {
     msgn "$Case_d"
     $POLDEK_NOCONF -s $REPO --mkidx --mt pdir || fail "mkidx failed"
-    die_if_empty_index "$REPO/packages.dir.gz"
+    die_if_empty_index "$REPO/packages.dir$COMPR_EXT"
 
     rm -rf $REPO/packages.*
     $POLDEK_NOCONF -s $REPO --st dir --mkidx --mt pdir || fail "mkidx failed"
-    die_if_empty_index "$REPO/packages.dir.gz"
+    die_if_empty_index "$REPO/packages.dir$COMPR_EXT"
 
     setUp
 
     msgn "$Case_e"
     $POLDEK_NOCONF -s $REPO --mkidx --mt pdir,pndir || fail "mkidx failed"
-    die_if_empty_index "$REPO/packages.ndir.gz"
-    die_if_empty_index "$REPO/packages.dir.gz"
+    die_if_empty_index "$REPO/packages.ndir$COMPR_EXT"
+    die_if_empty_index "$REPO/packages.dir$COMPR_EXT"
 }
 
 poldek_n() {
@@ -83,35 +83,36 @@ testCreateByName()
 {
     msgn "$Case_f"
     poldek_n -n repo-pndir --mkidx || fail "mkidx failed"
-    die_if_empty_index "$REPO/packages.ndir.gz"
+    die_if_empty_index "$REPO/packages.ndir$COMPR_EXT"
 
     # disabled as pdir indexes are gone since 0.4
 
     #poldek_n -n repo-pdir --mkidx || fail "mkidx failed"
-    #die_if_empty_index "$REPO/packages.dir.gz"
+    #die_if_empty_index "$REPO/packages.dir$COMPR_EXT"
 
     #setUp
 
     #poldek_n -n repo-pndir -n repo-pdir --mkidx || fail "-n 1 -n 2 --mkidx failed"
-    #die_if_empty_index "$REPO/packages.ndir.gz"
-    #die_if_empty_index "$REPO/packages.dir.gz"
+    #die_if_empty_index "$REPO/packages.ndir$COMPR_EXT"
+    #die_if_empty_index "$REPO/packages.dir$COMPR_EXT"
 }
 
-#  g) -s /foo --mkidx=/tmp/bar.gz
+#  g) -s /foo --mkidx=/tmp/bar$COMPR_EXT
 testNonDefaultName()
 {
     msgn "$Case_g"
     poldek="$POLDEK_NOCONF"
 
     $poldek -s $REPO --mkidx=$TMPDIR || fail "mkidx #1 failed"
-    die_if_empty_index "$TMPDIR/packages.ndir.gz"
+    die_if_empty_index "$TMPDIR/packages.ndir$COMPR_EXT"
 
-    $poldek -s $REPO --mkidx=$TMPDIR/packages.foo.ndir.gz || fail "mkidx #2 failed"
-    die_if_empty_index "$TMPDIR/packages.foo.ndir.gz"
+    $poldek -s $REPO --mkidx=$TMPDIR/packages.foo.ndir$COMPR_EXT || fail "mkidx #2 failed"
+    die_if_empty_index "$TMPDIR/packages.foo.ndir$COMPR_EXT"
 
-    $poldek --st pndir -s $TMP/packages.foo.ndir.gz \
-            --mkidx=$TMP/packages.foo2.ndir.gz --mt pndir || fail "mkidx #3 failed"
-    die_if_empty_index "$TMP/packages.foo2.ndir.gz"
+    $poldek --st pndir -s $TMP/packages.foo.ndir$COMPR_EXT \
+            --mkidx=$TMP/packages.foo2.ndir$COMPR_EXT --mt pndir || fail "mkidx #3 failed"
+
+    die_if_empty_index "$TMP/packages.foo2.ndir$COMPR_EXT"
 
     setUp
     $poldek -s $REPO --mkidx --mt pndir || fail "mkidx #4 failed"
@@ -119,25 +120,66 @@ testNonDefaultName()
 
     poldek="$POLDEK_UP -Ovfile_retries=1"
     $poldek --st pndir -s $REPOURL --mkidx=$TMPDIR fail "mkidx #5 failed"
-    die_if_empty_index "$TMPDIR/packages.ndir.gz"
+    die_if_empty_index "$TMPDIR/packages.ndir$COMPR_EXT"
 
-    $poldek --st pndir -s $REPOURL --mkidx=$TMPDIR/packages.foo.ndir.gz || fail "mkidx #6 failed"
-    die_if_empty_index "$TMPDIR/packages.foo.ndir.gz"
+    $poldek --st pndir -s $REPOURL --mkidx=$TMPDIR/packages.foo.ndir$COMPR_EXT || fail "mkidx #6 failed"
+    die_if_empty_index "$TMPDIR/packages.foo.ndir$COMPR_EXT"
 }
 
-#  h) -n foo --mkidx=/tmp/bar.gz
+#  h) -n foo --mkidx=/tmp/bar$COMPR_EXT
 testCreateFromRemoteRepos()
 {
-
     msgn "$Case_h"
-    poldek_n -n repo-pndir --mkidx=$TMPDIR/packages.foo.ndir.gz --mt pndir ||
+    poldek_n -n repo-pndir --mkidx=$TMPDIR/packages.foo.ndir$COMPR_EXT --mt pndir ||
         fail "mkidx #1 failed"
-    die_if_empty_index "$TMPDIR/packages.foo.ndir.gz"
+    die_if_empty_index "$TMPDIR/packages.foo.ndir$COMPR_EXT"
 
-    poldek_n -n repo-pndir --mkidx=$TMPDIR/packages.foo2.ndir.gz --mt pndir ||
+    poldek_n -n repo-pndir --mkidx=$TMPDIR/packages.foo2.ndir$COMPR_EXT --mt pndir ||
         fail "mkidx #2 failed"
 
-    die_if_empty_index "$TMPDIR/packages.foo2.ndir.gz"
+    die_if_empty_index "$TMPDIR/packages.foo2.ndir$COMPR_EXT"
 }
+
+testCreateConfiguredDefaultIndexCompr()
+{
+    msgn "with 'default index compr' = zst"
+    echo "
+[global]
+default index compr = zst
+" >> $TMPDIR/poldek.conf
+
+    if [ -n "$POLDEK_TESTING_INDEX_COMPR" ]; then # unset global
+        force_msg " => compression is set globally, skipped"
+        return;
+    fi
+
+    $POLDEK --conf $TMPDIR/poldek.conf -s $REPO --mkidx || fail "mkidx failed"
+    die_if_empty_index "$REPO/packages.ndir.zst"
+}
+
+testCreateWithIndexComprOption()
+{
+    compr="$POLDEK_TESTING_INDEX_COMPR"
+    if [ -n "$POLDEK_TESTING_INDEX_COMPR" ]; then # unset global
+        unset POLDEK_TESTING_INDEX_COMPR
+    fi
+
+    op=""
+    if [ "$compr" == "zst" ]; then
+        op="zstd"
+    elif [ "$compr" == "gz" ]; then
+        op="gzip"
+    elif [ "$compr" == "none" ]; then
+        op="nocompress"
+    else
+        op="gzip"
+    fi
+
+    msgn "with --mo=$op"
+
+    $POLDEK_NOCONF -s $REPO --mkidx --mo=$op || fail "mkidx failed"
+    die_if_empty_index "$REPO/packages.ndir$COMPR_EXT"
+}
+
 
 . ./sh/lib/shunit2
diff --git a/tests/sh/02-up-repo b/tests/sh/02-up-repo
--- a/tests/sh/02-up-repo
+++ b/tests/sh/02-up-repo
@@ -3,38 +3,42 @@
 
 . ./sh/lib/setup
 . ./sh/lib/repo-setup
+. ./sh/lib/compr-setup
 
 mkidx() {
    $POLDEK_NOCONF -s $REPO --mkidx --mt pndir || fail "mkidx failed"
 }
 
 up() {
-   $POLDEK_UP -Oautoupa=n -Osource="test,type=pndir $REPOURL" --up || fail "up failed"
+    $POLDEK_UP -Oautoupa=n -Osource="test,type=pndir $REPOURL" --up || fail "up failed"
 }
 
-testUpdate() 
+up_debug() {
+    echo $POLDEK_UP -Oautoupa=n -Osource="test,type=pndir $REPOURL" --up || fail "up failed"
+}
+
+testUpdate()
 {
     POLDEK_TESTING_DENIED_FILES="packages.ndir.diff.toc"
 
     rm -rf $REPO/*.rpm
     # Create repo and generate some diffs
     msg "\n## Creating empty index"
-    indexfile="$REPO/packages.ndir.gz"
+    indexfile="$REPO/packages.ndir$COMPR_EXT"
     mkidx
     die_if_invalid_index $indexfile 0
-    
-    msg "\n## up"
+
+    msg "\n## up #0"
     up
 
-    POLDEK_TESTING_DENIED_FILES="packages.ndir.gz"
-    msg "\n## Changing repo #1"    
+    POLDEK_TESTING_DENIED_FILES="packages.ndir$COMPR_EXT"
+    msg "\n## Changing repo #1"
     sleep 1
     add_package_to_repo
     mkidx
     die_if_invalid_index $indexfile 1
-    die_if_invalid_index "$REPO/packages.i/packages.ndir.diff.toc.gz" 1
-
-    msg "\n## up"
+    die_if_invalid_index "$REPO/packages.i/packages.ndir.diff.toc$COMPR_EXT" 1
+    msg "\n## up #1"
     up
 
     msg "\n## Changing repo #2"
@@ -42,20 +46,20 @@ testUpdate()
     remove_package_from_repo
     mkidx
     die_if_invalid_index $indexfile 0
-    die_if_invalid_index "$REPO/packages.i/packages.ndir.diff.toc.gz" 2
-    
-    msg "\n## up"
+    die_if_invalid_index "$REPO/packages.i/packages.ndir.diff.toc$COMPR_EXT" 2
+
+    msg "\n## up #2"
     up
 
     msg "\n## Changing repo #3"
     sleep 1
     add_package_to_repo
     add_package_to_repo
-    mkidx 
+    mkidx
     die_if_invalid_index $indexfile 2
-    die_if_invalid_index "$REPO/packages.i/packages.ndir.diff.toc.gz" 3
+    die_if_invalid_index "$REPO/packages.i/packages.ndir.diff.toc$COMPR_EXT" 3
 
-    msg "\n## up"
+    msg "\n## up #3"
     up
 
     # <https://bugs.pld-linux.org/show_bug.cgi?id=28>
@@ -64,7 +68,7 @@ testUpdate()
     rm -rf $REPO/packages.*
     add_package_to_repo
     mkidx
-    msg "\n## up"
+    msg "\n## up (reset)"
 
     POLDEK_TESTING_DENIED_FILES="packages.ndir.diff.toc"
     $POLDEK_UP -Oautoupa=n -Osource="test,type=pndir $REPOURL" --up >/dev/null
@@ -78,12 +82,12 @@ testUpdate()
     sleep 1
     add_package_to_repo
     mkidx
-    msg "\n## up"
+    msg "\n## up #4"
 
-    POLDEK_TESTING_DENIED_FILES="packages.ndir.gz"
+    POLDEK_TESTING_DENIED_FILES="packages.ndir$COMPR_EXT"
     $POLDEK_UP -Oautoupa=n -Osource="test,type=pndir $REPOURL" --up || fail "up failed"
 
-    POLDEK_TESTING_DENIED_FILES=".gz" # should be up to date
+    POLDEK_TESTING_DENIED_FILES="$COMPR_EXT" # should be up to date
     $POLDEK_UP -Oautoupa=n -Osource="test,type=pndir $REPOURL" --up || fail "up failed"
     $POLDEK_UP -Oautoupa=n -Osource="test,type=pndir $REPOURL" --upa || fail "up failed"
 
@@ -93,20 +97,20 @@ testUpdate()
     sleep 1
     add_package_to_repo
     mkidx
-    msg "\n## up"
+    msg "\n## up #5"
 
-    POLDEK_TESTING_DENIED_FILES="" 
-    lastdiff=$(ls -tr $REPO/packages.i/packages.ndir.*.*.*-*.*.*.gz | tail -1)
+    POLDEK_TESTING_DENIED_FILES=""
+    lastdiff=$(ls -tr $REPO/packages.i/packages.ndir.*.*.*-*.*.*$COMPR_EXT | tail -1)
     [ -z "$lastdiff" ] && fail "no last diff?"
     msg "lastdiff $lastdiff"
     rm -f "$lastdiff"
     $POLDEK_UP -Oautoupa=y -Osource="test,type=pndir $REPOURL" --up
     if [ $? -eq 0 ]; then
-        echo "THE ERROR ABOVE is EXPECTED"
-    else    
+        force_msg "THE ERROR ABOVE is EXPECTED"
+    else
         fail "up"
-    fi    
-    
+    fi
+
 }
 
 . ./sh/lib/shunit2
