make tests pass again

diff --git a/tests/sh/lib/repo-setup b/tests/sh/lib/repo-setup
--- a/tests/sh/lib/repo-setup
+++ b/tests/sh/lib/repo-setup
@@ -10,11 +10,22 @@ setUp() {
     tearDown
 }
 
+build_repo_packages() {
+    local n=$(find $SOURCE_REPO/ -name \*.rpm | wc -l)
+    if [ $n -lt 20 ]; then
+        for i in a b c d e f g h i j k l m n o p r s t u w x y z; do
+            rpm="$i-1-1.noarch.rpm"
+            [ -f "$SOURCE_REPO/$rpm" ] && continue
+            ./build-test-rpm.sh -d $SOURCE_REPO/ -n $i -v 1  >/dev/null 2>&1 || fail "build package $i failed"
+        done
+    fi
+}
+
 oneTimeSetUp() {
     [ ! -d "$PWD/sh/lib" ] && fail "$PWD is not a tests directory (missing sh/lib)"
 
     SHLIBDIR="$PWD/sh/lib"
-    
+
     SOURCE_REPO=${SOURCE_REPO:-"${PWD}/repo"}
     [ ! -d "$SOURCE_REPO" ] && fail "$SOURCE_REPO: no such directory"
 
@@ -25,11 +36,13 @@ oneTimeSetUp() {
     TMP="${TMP}/poldek-tests"
     TMPDIR="$TMP"
 
+    export TMP TMPDIR
+
     rm -rf $TMPDIR
     mkdir -p $TMPDIR
     [ ! -d $TMPDIR ] && fail "$TMPDIR: no such directory"
 
-    
+
     CACHEDIR="$TMPDIR/kesz"
     rm -rf $CACHEDIR
     mkdir -p $CACHEDIR
@@ -46,12 +59,19 @@ oneTimeSetUp() {
     POLDEK="$PWD/../cli/poldek $QUIET"
     POLDEK_NOCONF="$POLDEK --noconf -Ovfile_retries=1 --cachedir $CACHEDIR"
     POLDEK_UP="$POLDEK --conf ./sh/lib/vftest-fetch.conf --cachedir $CACHEDIR"
+
+    build_repo_packages
     ln -sf $SOURCE_REPO/*.rpm $REPO/ || fail
     tearDown
 }
 
 poldek_up() {
     $POLDEK_UP -Osource="test,type=pndir $REPOURL" $@
+}
+
+poldek_quiet_up() {
+    local cmd=$(echo $POLDEK_UP | sed 's|\-v|-q|g');
+    $cmd -Osource="test,type=pndir $REPOURL" $@
 }
 
 oneTimeTearDown() {
@@ -63,7 +83,7 @@ oneTimeTearDown() {
 
 die_if_empty_index() {
     die_if_invalid_index $1 ""
-}    
+}
 
 die_if_invalid_index() {
     anindex=$1
@@ -87,7 +107,7 @@ die_if_invalid_index() {
     if zgrep -q '^tndb[0-9]\.[0-9]' $anindex; then
        anindex_real_type="pndir"
     fi
-    
+
     if [ "$anindex_real_type" != "$anindex_type" ]; then
         fail "invalid $anindex type $anindex_type, real is $anindex_real_type"
     fi
@@ -98,7 +118,7 @@ die_if_invalid_index() {
         fi
     fi
 
-    if [ -n "$expected_packages" ]; then 
+    if [ -n "$expected_packages" ]; then
        if ! zgrep -q "Contains $expected_packages packages" $anindex; then
             fail "$anindex: number of packages mismatch"
        fi
@@ -107,7 +127,7 @@ die_if_invalid_index() {
 
 
 add_package_to_repo() {
-    for p in $(ls $SOURCE_REPO/*.rpm); do 
+    for p in $(ls $SOURCE_REPO/*.rpm); do
         [ ! -f $p ] && fail "no packages in $SOURCE_REPO?"
         package=$(basename $p)
 
@@ -142,7 +162,7 @@ random_change_repo() {
 
     for i in $SOURCE_REPO/${to_add}*.rpm; do
         bn=$(basename $i);
-          
+
         [ ! -f $i ] && continue;
         [ -f $REPO/$bn ] && continue;
 
@@ -153,13 +173,13 @@ random_change_repo() {
 
     for i in $REPO/${to_del}*.rpm; do
         bn=$(basename $i);
-          
+
         [ ! -f $i ] && continue
         msg "   - rm $bn"
         rm -f $i
         nremoved=$(expr $nremoved + 1)
-    done 
-	
+    done
+
 
     nchanges=$(expr $nadded + $nremoved)
     [ "$nchanges" = "0" ] && random_change_repo
