Up tests

diff --git a/tests/sh/01-create-repo b/tests/sh/01-create-repo
--- a/tests/sh/01-create-repo
+++ b/tests/sh/01-create-repo
@@ -6,9 +6,9 @@
 #  Index creation use cases:
 Case_a="-s /foo                   =>  dir  -> default type"
 Case_b="--st type -s /foo         =>  type -> default type"
-Case_c="--st type /foo --mt dtype =>  type -> dtype"
-Case_d="-s /foo --mt dtype        =>  dir  -> dtype"
-Case_e="-s /foo --mt dtype,dtype2 =>  dir  -> dtype"
+#Case_c="--st type /foo --mt dtype =>  type -> dtype" # irrelevant, as pndir is only creatable format
+#Case_d="-s /foo --mt dtype        =>  dir  -> dtype" # irrelevant, as pndir is only creatable format
+#Case_e="-s /foo --mt dtype,dtype2 =>  dir  -> dtype" # irrelevant, as pndir is only creatable format
 Case_f="-n foo                    =>  dir (or original type) -> foo's type"
 Case_g="-s /foo --mkidx=/tmp/bar.gz"
 Case_h="-n foo --mkidx=/tmp/bar.gz"
@@ -30,32 +30,44 @@ testCreateDefaultType()
     fi
 }
 
-#  b) --st type -s /foo         =>  type -> default type
-#  c) --st type /foo --mt type  =>  type -> dtype
-XXXtestConvertRepos()           # disabled as pdir indexes are gone since 0.4
+#  b) --st dir -s /foo          =>  dir -> default type
+testCreateFromDir()
 {
-    $POLDEK_NOCONF -s $REPO --mkidx || fail "mkidx failed"
+    $POLDEK_NOCONF --st dir -s $REPO --index || fail "mkidx failed"
     die_if_empty_index "$REPO/packages.ndir$COMPR_EXT"
 
-    rm -rf $TMPDIR/packages.*
-    cp $REPO/packages.ndir.* $TMPDIR || fail "cp failed"
+    # move indexes to separate dir to make sure poldek will not faillback to load it as "dir" repo
+    rm -rf $TMPDIR/tmprepo
+    mkdir $TMPDIR/tmprepo
+    mv $REPO/packages.ndir* $TMPDIR/tmprepo || fail "cp failed"
 
+    check_repo_content $TMPDIR/tmprepo
+}
 
-    # c) --st type /foo --mt type =>  type -> dtype
-    msgn "$Case_c"
-    $POLDEK_NOCONF --st pndir -s $TMPDIR --mkidx --mt=pdir || fail "$Case_c failed"
-    die_if_empty_index "$TMPDIR/packages.dir$COMPR_EXT"
+#  b) --st rpmdb -s /foo          =>  rpmdb -> default type
+testCreateFromRpmdb() {
+    rm -rf $TMPDIR/tmproot
+    mkdir $TMPDIR/tmproot
+    rpm --root=$TMPDIR/tmproot --initdb
 
-    # b) --st type -s /foo
-    msgn "$Case_b"
-    rm -f $TMPDIR/packages.ndir*
-    $POLDEK_NOCONF --st pdir -s $TMPDIR --mkidx || fail "$Case_b failed"
-    die_if_empty_index "$TMPDIR/packages.ndir$COMPR_EXT"
+    local rpmop=
+    test is_verbose_mode && rpmop="v"
+
+    msgn "prep: rpm install"
+    rpm --root=$TMPDIR/tmproot -U$rpmop $SOURCE_REPO/sh-*.rpm --noscripts
+    for p in $(ls $SOURCE_REPO/a*.rpm); do
+        rpm --root=$TMPDIR/tmproot -U$rpmop $p --noscripts
+    done
+
+    msgn "test"
+    $POLDEK_NOCONF --st rpmdb -s $TMPDIR/tmproot/var/lib/rpm --index=$TMPDIR/tmproot/packages.ndir$COMPR_EXT || fail "mkidx failed"
+    die_if_empty_index "$TMPDIR/tmproot/packages.ndir$COMPR_EXT"
+    check_repo_content $TMPDIR/tmproot
 }
 
 #  d) -s /foo --mt dtype        =>  dir  -> dtype
 #  e) -s /foo --mt dtype,dtype2 =>  dir  -> dtype
-XXXtestSelectType() # disabled as pdir indexes are gone since 0.4
+xtestSelectType() # disabled as pdir indexes are gone since 0.4
 {
     msgn "$Case_d"
     $POLDEK_NOCONF -s $REPO --mkidx --mt pdir || fail "mkidx failed"
diff --git a/tests/sh/03-up-loop b/tests/sh/03-up-loop
--- a/tests/sh/03-up-loop
+++ b/tests/sh/03-up-loop
@@ -44,6 +44,14 @@ load() {
       fi
   done
 
+  for p in $packages; do
+      name=$(echo $p | cut -f1 -d-)
+      files=$($POLDEK_UP -q --skip-installed -Osource="test,type=pndir $REPOURL" -n test desc -ll $p | grep '/' | cut -f2)
+      msg "pkg $name, files: $files"
+      echo $files | grep -q "/bin/$name"; [ $? -eq 0 ] || fail "/bin/$name: no file"
+      echo $files | grep -q "/usr/share/doc/$name/README"; [ $? -eq 0 ] || fail "/usr/share/doc/$name/README: no file"
+  done
+
   return $ec
 }
 
diff --git a/tests/sh/lib/repo-setup b/tests/sh/lib/repo-setup
--- a/tests/sh/lib/repo-setup
+++ b/tests/sh/lib/repo-setup
@@ -21,11 +21,13 @@ build_repo_packages() {
         for i in a b c d e f g h i j k l m n o p r s t u w x y v z; do
             rpm="$i-1-1.noarch.rpm"
             [ -f "$SOURCE_REPO/$rpm" ] && continue
-            ./build-test-rpm.sh -d $SOURCE_REPO/ -n $i -v 1  >/dev/null 2>&1 || abort "build package $i failed"
-            ./build-test-rpm.sh -d $SOURCE_REPO/ -n "$i$i" -v 1  >/dev/null 2>&1 || abort "build package $i$i failed"
-            ./build-test-rpm.sh -d $SOURCE_REPO/ -n "$i$i$i" -v 1  >/dev/null 2>&1 || abort "build package $i$i$i failed"
+            ./build-test-rpm.sh -d $SOURCE_REPO/ -n $i -f /bin/$i -f /usr/share/doc/$i/README -v 1  >/dev/null 2>&1 || abort "build package $i failed"
+            ./build-test-rpm.sh -d $SOURCE_REPO/ -n "$i$i" -f /bin/$i$i -f /usr/share/doc/$i$i/README -v 1  >/dev/null 2>&1 || abort "build package $i$i failed"
+            ./build-test-rpm.sh -d $SOURCE_REPO/ -n "$i$i$i" -f /bin/$i$i$i -f /usr/share/doc/$i$i$i/README -v 1  >/dev/null 2>&1 || abort "build package $i$i$i failed"
         done
     fi
+    local i=sh
+    ./build-test-rpm.sh -d $SOURCE_REPO/ -n $i -f /bin/$i -f /usr/share/doc/$i/README -v 1  >/dev/null 2>&1 || abort "build package $i failed"
 }
 
 build_package() {
@@ -136,8 +138,8 @@ die_if_empty_index() {
 }
 
 die_if_invalid_index() {
-    anindex=$1
-    expected_packages=$2
+    local anindex=$1
+    local expected_packages=$2
 
     GREP="zgrep"
     CAT="zcat"
@@ -158,9 +160,9 @@ die_if_invalid_index() {
     fi
 
     if echo $anindex | grep -q "diff.toc"; then
-        expected_lines="$expected_packages"
+        local expected_lines="$expected_packages"
 
-        lines=$($CAT $anindex | wc -l)
+        local lines=$($CAT $anindex | wc -l)
         if [ "$lines" != "$expected_lines" ]; then
             fail "$anindex contains $lines lines, expected $expected_lines"
         fi
@@ -191,6 +193,47 @@ die_if_invalid_index() {
             fail "$anindex: number of packages mismatch"
        fi
     fi
+}
+
+check_repo_content() {
+    local repo=$1
+    local limit=${2:-"10"}
+
+    if [ -z "$repo" ]; then
+        fail "check_repo_content(): missing repo arg"
+        return 1
+    fi
+
+    msgn "check_repo_content $repo limit=$limit"
+    msg "$POLDEK_NOCONF -v -s $repo --skip-installed --cmd \"ls --qf '%{NAME}\n'\""
+
+    local packages=$($POLDEK_NOCONF -q -s $repo --skip-installed ls --qf '%{NAME}\n');
+    msg "$POLDEK_NOCONF -v -s $repo --skip-installed --cmd 'desc -L *'"
+    $POLDEK_NOCONF -q --skip-installed -s $repo --cmd 'desc -L *' > $TMPDIR/changelogs
+
+    local n=0
+    for p in $packages; do
+        n=$(expr $n + 1)
+        [ $n -gt $limit ] && break
+
+        #msg "package $p"
+
+        # check changelog
+        grep -qP "^\- $p package changelog entry" $TMPDIR/changelogs
+        if [ $? -ne 0 ]; then
+          msgn "$POLDEK_UP -q --skip-installed -s $repo --cmd 'desc -L $p'"
+          fail "$p: missing changelog"
+          break
+        fi
+
+        # check files
+        local files=$($POLDEK_NOCONF -q --skip-installed -s $repo desc -ll $p | grep '/' | cut -f2)
+        #msg "pkg $name, files: $files"
+        echo $files | grep -q "/bin/$p"; [ $? -eq 0 ] || fail "/bin/$p: no file"
+        echo $files | grep -q "/usr/share/doc/$p/README"; [ $? -eq 0 ] || fail "/usr/share/doc/$p/README: no file"
+    done
+    [ $n -eq 0 ] && fail "$repo empty repo?"
+    return 0;
 }
 
 
