tests: check changelogs presence (related to #6)

diff --git a/tests/sh/03-up-loop b/tests/sh/03-up-loop
--- a/tests/sh/03-up-loop
+++ b/tests/sh/03-up-loop
@@ -20,11 +20,29 @@ load() {
   $POLDEK_NOCONF -q --skip-installed --st pndir -s $REPO \
            --cmd 'desc -al *' | egrep -v '^Path:' > $TMPDIR/remote-dump
 
-  #less         $TMPDIR/remote-dump
-  #ls -l $TMPDIR/remote-dump $TMPDIR/local-dump
+
+  # comare local and remote index contents
   diff -q $TMPDIR/remote-dump $TMPDIR/local-dump
-  ec=$?
-  [ $ec -ne 0 ] && echo "repo=$REPO" && ls -l $TMPDIR/remote-dump $TMPDIR/local-dump
+  local ec=$?
+  if [ $ec -ne 0 ]; then
+      echo "repo=$REPO" && ls -l $TMPDIR/remote-dump $TMPDIR/local-dump
+      return $ec
+  fi
+
+  # check if changelogs are available (related to github#6)
+  packages=$($POLDEK_UP -q --skip-installed -Osource="test,type=pndir $REPOURL" -n test \
+                            --cmd ls --qf '%{NAME}\n')
+  $POLDEK_UP -q --skip-installed -Osource="test,type=pndir $REPOURL" -n test --cmd 'desc -L *' > $TMPDIR/changelogs
+  for p in $packages; do
+      grep -qP "^\- $p package changelog entry" $TMPDIR/changelogs
+      ec=$?
+      if [ $ec -ne 0 ]; then
+          msgn "$POLDEK_UP -q --skip-installed -Osource='test,type=pndir $REPOURL' -n test --cmd desc -L $p"
+          fail "$p: missing changelog"
+          break
+      fi
+  done
+
   return $ec
 }
 
diff --git a/tests/sh/lib/repo-setup b/tests/sh/lib/repo-setup
--- a/tests/sh/lib/repo-setup
+++ b/tests/sh/lib/repo-setup
@@ -18,11 +18,12 @@ abort() {
 build_repo_packages() {
     local n=$(find $SOURCE_REPO/ -name \*.rpm | wc -l)
     if [ $n -lt 20 ]; then
-        for i in a b c d e f g h i j k l m n o p r s t u w x y z; do
+        for i in a b c d e f g h i j k l m n o p r s t u w x y v z; do
             rpm="$i-1-1.noarch.rpm"
             [ -f "$SOURCE_REPO/$rpm" ] && continue
             ./build-test-rpm.sh -d $SOURCE_REPO/ -n $i -v 1  >/dev/null 2>&1 || abort "build package $i failed"
-            ./build-test-rpm.sh -d $SOURCE_REPO/ -n "$i$i" -v 1  >/dev/null 2>&1 || abort "build package $i failed"
+            ./build-test-rpm.sh -d $SOURCE_REPO/ -n "$i$i" -v 1  >/dev/null 2>&1 || abort "build package $i$i failed"
+            ./build-test-rpm.sh -d $SOURCE_REPO/ -n "$i$i$i" -v 1  >/dev/null 2>&1 || abort "build package $i$i$i failed"
         done
     fi
 }
